# Generated by Django 2.1.7 on 2019-06-20 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(choices=[('Monitoring HQ', 'MonitoringHq'), ('Enugu Zonal Office', 'EnuguOffice'), ('Registrars Office', 'CEO'), ('Finance & Accounts', 'FAH')], max_length=20)),
                ('role', models.CharField(choices=[('Monitoring', 'Monitoring'), ('ZonalOffices', 'ZonalOffices'), ('Registrar', 'Registrar'), ('Finance', 'Finance')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
