# Generated by Django 2.1.7 on 2019-06-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='radiographers',
            field=models.TextField(blank=True),
        ),
    ]
