# Generated by Django 2.1.7 on 2019-06-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_hospital_radiographers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='radiographers',
            field=models.CharField(max_length=200),
        ),
    ]
