# Generated by Django 2.1.7 on 2019-06-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0003_auto_20190603_2050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Licenses',
            new_name='License',
        ),
    ]
