# Generated by Django 2.1.7 on 2019-06-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0004_auto_20190603_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
