# Generated by Django 2.1.7 on 2019-06-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0006_auto_20190603_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
