# Generated by Django 2.1.7 on 2019-06-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0007_hospital_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired')], max_length=10),
        ),
    ]
