# Generated by Django 2.1.7 on 2019-10-31 07:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.IntegerField(blank=True, default=1000)),
                ('centre_name', models.CharField(max_length=200)),
                ('rc_number', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cac_certificate', models.ImageField(blank=True, upload_to='%Y/%m/%d/')),
                ('practice_license', models.ImageField(blank=True, upload_to='%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.IntegerField(default=100000, primary_key=True, serialize=False, unique=True)),
                ('hospital_name', models.CharField(max_length=200)),
                ('rc_number', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('services', models.TextField(blank=True)),
                ('equipment', models.TextField(blank=True)),
                ('radiographers', models.CharField(blank=True, max_length=200)),
                ('photo_main', models.ImageField(blank=True, upload_to='media/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='media/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='media/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='media/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='media/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='media/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='media/%Y/%m/%d/')),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cac_certificate', models.ImageField(blank=True, upload_to='%Y/%m/%d/')),
                ('practice_license', models.ImageField(blank=True, upload_to='%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.CharField(max_length=100)),
                ('license_category', models.CharField(max_length=100)),
                ('issue_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('expiry_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired')], max_length=10)),
                ('hospital_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.Hospital')),
            ],
        ),
    ]
