# Generated by Django 2.1.7 on 2019-10-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='id',
            field=models.AutoField(default=100000, primary_key=True, serialize=False, unique=True),
        ),
    ]
