# Generated by Django 2.1.7 on 2019-09-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='cac_certificate',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='centre',
            name='practice_license',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
