# Generated by Django 2.1.7 on 2019-09-27 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_auto_20190926_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='reg_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
