# Generated by Django 2.1.7 on 2019-10-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_auto_20191031_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='id',
            field=models.IntegerField(default=100000, primary_key=True, serialize=False, unique=True),
        ),
    ]
