# Generated by Django 2.1.7 on 2019-09-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_centre_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='application_no',
            field=models.IntegerField(blank=True, default=1000),
        ),
    ]
