# Generated by Django 2.1.7 on 2019-09-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_centre_application_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='photo_6',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='photo_main',
        ),
        migrations.AlterField(
            model_name='centre',
            name='cac_certificate',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='centre',
            name='practice_license',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d/'),
        ),
    ]
