# Generated by Django 2.1.7 on 2019-10-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_auto_20190930_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d/'),
        ),
    ]
